kind = "web"
previewPath = "/"
title = "PhotoZeePortfolio"
version = "1.0.0"
id = "artifacts/photozee-portfolio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25777

[services.development]
run = "pnpm --filter @workspace/photozee-portfolio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/photozee-portfolio", "run", "build" ]
publicDir = "artifacts/photozee-portfolio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25777"
BASE_PATH = "/"
